# -*- coding: utf-8 -*-
"""Lab02-Q2-Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARDUwYsEe2WNVEKQRxsvfgc2Pe17MkJS
"""

from google.colab import drive
drive.mount('/content/drive/')

file_path = '/content/drive/MyDrive/CS512/Data.txt'

import pandas as pd

# 1. OriginalMatrix = read the data from the file
OriginalMatrix = pd.read_csv(file_path, sep="\t", index_col=False)
# 2. Print OriginalMatrix
OriginalMatrix

# 3. Matrix1 = Use OriginalMatrix to remove the columns that only include Zero or junk
OriginalMatrix = OriginalMatrix.dropna(axis=0, how='all') # Drop rows that are completely NaN
OriginalMatrix = OriginalMatrix.fillna('JUNK') # replace any leftover NaNs and convert to 'junk'
Matrix1 = OriginalMatrix.dropna(axis=1, how='all')  # drop all-NaN cols first
Matrix1 = Matrix1.loc[:, (Matrix1 != 0).any(axis=0)]  # drop cols with only zeros
# 4. Print Matrix1
Matrix1

# 5. Matrix2 = Use Matrix1 to remove the columns in which they have at least 5 cells which are junks
# or zero (non-numbers).
def is_junk_or_zero(x):
    try:
        val = float(x)
        return val == 0
    except:
        return True

Matrix2 = Matrix1.copy()
drop_cols = []
for col in Matrix2.columns:
    count = sum(Matrix2[col].apply(is_junk_or_zero))
    if count >= 5:
        drop_cols.append(col)
Matrix2 = Matrix2.drop(columns=drop_cols)
# 6. Print Matrix2
Matrix2

# 7. Matrix3 = Use Matrix2 to remove the rows in which they have at least 5 cells which are junks
# (non-numbers). Otherwise, if they have less than 5 junk values, replace the junk values with
# median of that row.
Matrix3 = Matrix2.copy()
rows_to_drop = []
for idx, row in Matrix3.iterrows():
    junk_mask = row.apply(lambda x: is_junk_or_zero(x))
    junk_count = junk_mask.sum()
    if junk_count >= 5:
        rows_to_drop.append(idx)
    else:
        # replace junk/zeros with row median
        row_numeric = pd.to_numeric(row, errors='coerce')
        median_val = row_numeric[row_numeric != 0].median()
        row[junk_mask] = median_val
        Matrix3.loc[idx] = row

Matrix3 = Matrix3.drop(index=rows_to_drop)
# 8. Print Matrix3
Matrix3

import numpy as np
# - RescaledMatrix = Do Rescaling (Standardization) of Matrix3.
Matrix3 = Matrix3.apply(pd.to_numeric, errors='coerce') # Convert all data to numeric for scaling
# - The code for Standardization is:
# x_standarization = (x – mean(X)) / (StdDev(X))
RescaledMatrix = (Matrix3 - Matrix3.mean()) / Matrix3.std(ddof=0)  # population std
# - Print RescaledMatrix
RescaledMatrix

# Normalize the standardized matrix.
# - NormalizedMatrix = Normalize Matrix3. The code for normalization is:
# x_Normalization = (x – min(X)) / ((max(X) – min(X)))
NormalizedMatrix = (RescaledMatrix - RescaledMatrix.min()) / (RescaledMatrix.max() - RescaledMatrix.min())
# - Print NormalizedMatrix
NormalizedMatrix